export const mockupFirst = {
  cookieName: "",
  title: `Опрос удовлетворенности пациента условиями оказания медицинской помощи ФГБУ 'НМИЦ онкологии им. Н.М Петрова 1 Минздрава России'` ,
  'event_id': '1',
    locale: 'ru',
  questions: [
    {
      type: "radiogroup",
      name: "1",
      title: "Вы пациент или родственник пациента?",
      isRequired: true,
      choices: ["Пациент", "Родственник"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "2",
      visibleIf: "{1}='Родственник'",
      title: "Укажите пол Родственика",
      isRequired: true,
      choices: ["Мужчина", "Женщина"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "3",
      visibleIf: "{1}='Родственник'",
      title: "Укажите возраст Родственика",
      isRequired: true,
      choices: [
        "18 – 24",
        "25 – 34",
        "35 – 44",
        "45 – 54",
        "55 – 64",
        "65 – 74",
        "75 лет или старше",
      ],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "4",
      visibleIf: "{1}='Пациент'",
      title: "Укажите Ваш пол",
      isRequired: true,
      choices: ["Мужчина", "Женщина"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "5",
      visibleIf: "{1}='Пациент'",
      title: "Укажите Ваш возраст",
      isRequired: true,
      choices: [
        "18 – 24",
        "25 – 34",
        "35 – 44",
        "45 – 54",
        "55 – 64",
        "65 – 74",
        "75 лет или старше",
      ],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "6",
      title:
        "Откуда вы узнали о ФГБУ «НМИЦ онкологии им. Н.Н. Петрова» Минздрава России (далее – НМИЦ)?",
      isRequired: true,
      hasOther: true,
      otherText: "Другое",
      choices: [
        "Реклама (наружная)",
        "Интернет",
        "Рекомендация знакомого",
        "Телевидение",
      ],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "7",
      title: "Вы получили лечение",
      isRequired: true,
      choices: ["В дневном стационаре", "В круглосуточном стационаре"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "6",
      title:
        "Получили ли Вы приглашение на госпитализацию на бумажном носителе от врача НМИЦ?",
      isRequired: true,
      choices: ["Да", "Нет"],
      colCount: 0,
    },
    {
        type: "radiogroup",
        name: "9",
        title:
          "Были ли Вам разъяснены правила (условия) госпитализации в НМИЦ?",
        isRequired: true,
        visibleIf: "{6}='Да'",
        choices: ["Да", "Нет"],
        colCount: 0,
      },
    {
      type: "text",
      name: "10",
      visibleIf: "{6}='Да'",
      title:
        "Укажите срок ожидания плановой госпитализации с момента получения направления на госпитализацию (количество дней)",
      isRequired: true,
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "11",
      title:
        "До госпитализации Вам назначались диагностические исследования в НМИЦ?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
        type: "text",
        name: "12",
        title:
          "Сколько времени Вы ожидали проведения исследования?",
        isRequired: true,
        colCount: 0,
      },
      {
        type: "radiogroup",
        name: "13",
        title:
          "Исследование проведено в дату и  время, установленные  при записи",
        isRequired: true,
        colCount: 0,
        choices: ["Да", "Нет"],
      },

    {
      type: "radiogroup",
      name: "14",
      title: "Имеете ли Вы установленную группу ограничения трудоспособности?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "15",
      title: "Удовлетворены ли Вы условиями пребывания в приемном отделении?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "16",
      title: "Что именно Вас не удовлетворяет?",
      isRequired: true,
      colCount: 0,
      hasOther: true,
      visibleIf: "{10}='Нет'",
      otherText: "Другое",
      choices: [
        "Отсутствие свободных мест ожидания",
        "Состояние гардероба",
        "Состояние туалета",
        "Отсутствие питьевой воды",
        "Санитарные условия",
      ],
    },
    {
      type: "radiogroup",
      name: "17",
      title:
        "Сколько времени Вы провели в приемном отделении при госпитализации?",
      isRequired: true,
      colCount: 0,
      choices: [
        "Более 2 часов",
        "От 1 до 2 часов",
        "От 30 минут до часа",
        "Менее 30 минут",
      ],
    },
    {
      type: "radiogroup",
      name: "18",
      title:
        "Удовлетворены ли Вы отношением персонала во время пребывания в приемном отделении (доброжелательность, вежливость)?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "19",
      title:
        "Удовлетворены ли Вы навигацией внутри НМИЦ (предоставлением информации о размещении кабинетов медицинских работников, лабораторных и диагностических подразделений, санитарно-гигиенических помещений и др.)?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "20",
      title:
        "Сколько времени Вы провели в ожидании Вашего лечащего врача после госпитализации в отделение?",
      isRequired: true,
      colCount: 0,
      choices: [
        "Более 2 часов",
        "От 1 до 2 часов",
        "От 30 минут до часа",
        "Менее 30 минут",
      ],
    },
    {
      type: "radiogroup",
      name: "21",
      title: "Где Вы ожидали первичного осмотра лечащего врача?",
      isRequired: true,
      colCount: 0,
      otherText: "Другое",
      choices: ["В коридоре", "В палате"],
    },
    {
      type: "radiogroup",
      name: "22",
      title: "Кто проводил Ваш первичный осмотр?",
      isRequired: true,
      colCount: 0,
      choices: [
        "Ваш лечащий врач",
        "Помощник врача (ординатор)",
        "Дежурный врач",
        "Врач не представился",
      ],
    },

        {
          type: "rating",
          name: "23",
          title: "Вас внимательно выслушали",
          isRequired: true,
          choices: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
          minRateDescription: "Не удовлетворены",
          maxRateDescription: "Удовлеторены",
        },
        {
          type: "rating",
          name: "24",
          isRequired: true,
          title: "Вам ответили на все Ваши вопросы",
          rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
          minRateDescription: "Не удовлетворены",
          maxRateDescription: "Удовлеторены",
        },
        {
          type: "rating",
          name: "25",
          title: "Вашей проблеме уделили должное внимание",
          isRequired: true,
          rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
          minRateDescription: "Не удовлетворены",
          maxRateDescription: "Удовлеторены",
        },
        {
          type: "rating",
          name: "26",
          isRequired: true,
          title: "Врач был учтив и вежлив",
          rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
          minRateDescription: "Не удовлетворены",
          maxRateDescription: "Удовлеторены",
        },
  
    {
      type: "radiogroup",
      name: "27",
      title: "Какое лечение Вам проводилось?",
      isRequired: true,
      colCount: 0,
      choices: [
        "Оперативное (хирургическое)",
        "Лекарственное",
        "Лучевая терапия",
      ],
    },
    {
      type: "radiogroup",
      name: "28",
      title:
        "Возникала ли у Вас во время пребывания в стационаре необходимость оплачивать назначенные лекарственные средства за свой счет?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "text",
      name: "29",
      title: "Сколько дней продлилась Ваша госпитализация?",
      isRequired: true,
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "30",
      title: "После выписки врач объяснил Вам свои рекомендации?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет", "Частично", "Только после Вашей просьбы"],
    },
    {
      type: "rating",
      name: "31",
      isRequired: true,
      title:
        "Насколько Вы удовлетворены качеством выполнения обязанностей младшим медицинским персоналом Вашего отделения (санитарки, буфетчицы)?",
      rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      minRateDescription: "Не удовлетворены",
      maxRateDescription: "Удовлеторены",
    },
    {
      type: "rating",
      name: "32",
      isRequired: true,
      title:
        "Насколько Вы удовлетворены работой среднего медицинского персонала отделения (медицинские сестры)?",
      rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      minRateDescription: "Не удовлетворены",
      maxRateDescription: "Удовлеторены",
    },
    {
      type: "rating",
      name: "33",
      isRequired: true,
      title:
        "Насколько Вы удовлетворены отношением к Вам персонала отделения (культура общения, внимание, доброжелательность, ответы на Ваши вопросы)?",
      rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      minRateDescription: "Не удовлетворены",
      maxRateDescription: "Удовлеторены",
    },
    {
      type: "rating",
      name: "33",
      isRequired: true,
      title: "Насколько Вы удовлетворены питанием во время пребывания в НМИЦ?",
      rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      minRateDescription: "Не удовлетворены",
      maxRateDescription: "Удовлеторены",
    },
    {
      type: "radiogroup",
      name: "34",
      title: "Сколько раз в день проводилась уборка Вашей палаты?",
      isRequired: true,
      choices: [
        "Не проводилась",
        "1 раз в день",
        "Более 1 раза в день",
        "Затрудняюсь ответить",
      ],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "35",
      title: "Проводится ли обработка тумбочек в Вашей палате?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет", "Затрудняюсь ответить"],
    },
    {
      type: "radiogroup",
      name: "36",
      title:
        "Были ли отмечены по отношению к Вам нарушения этики (грубость, невежливое обращение) со стороны медицинского персонала?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "37",
      title: "Случались ли конфликтные ситуации в отделении?",
      isRequired: true,
      choices: ["Да", "Нет"],
      colCount: 0,
    },
    {
      type: "rating",
      name: "38",
      isRequired: true,
      title:
        "Отметьте, насколько Вы удовлетворены оказанной медицинской помощью в НМИЦ",
      rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      minRateDescription: "Не удовлетворены",
      maxRateDescription: "Удовлеторены",
    },
    {
      type: "radiogroup",
      name: "39",
      title: "Сколько времени Вы ожидали проведения исследования",
      isRequired: true,
      colCount: 0,
      choices: [
        "14 календарных дней и более",
        "От 7 до 14 дней",
        "Менее 7 дней",
      ],
    },
    {
      type: "radiogroup",
      name: "40",
      title: "Исследование проведено в дату и время, установленные при записи?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "41",
      title: "Какая у Вас установлена группа инвалидности?",
      isRequired: true,
      colCount: 0,
      choices: ["I", "II", "III"],
    },
    {
      type: "radiogroup",
      name: "42",
      title:
        "По Вашему мнению, оборудован ли НМИЦ всем необходимым для доступа лиц с ограниченными возможностями?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "checkbox",
      name: "43",
      title:
        "Отметьте, чего не хватает для комфортного пребывания пациентов с ограниченными возможностями?",
      isRequired: true,
      colCount: 0,
      choices: [
        "Специального подъезда и парковки для автотранспорта",
        "Пандусов, поручней",
        "Электрических подъемников",
        "Специальных лифтов",
        "Голосовых сигналов",
        "Информационных бегущих строк, информационных стендов",
        "Информации для слабовидящих людей шрифтом Брайля",
        "Специально оборудованных санитарно-гигиенических помещений",
        "Сменных кресел-колясок",
      ],
    },
    {
      type: "radiogroup",
      name: "44",
      title:
        "Объяснил ли Вам врач цель и риски операции, а также ход операции?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "45",
      title: "Во время осмотра анестезиологом всё ли Вам было разъяснено?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "radiogroup",
      name: "46",
      title: "Находились ли Вы в реанимации после оперативного вмешательства?",
      isRequired: true,
      colCount: 0,
      choices: ["Да", "Нет"],
    },
    {
      type: "rating",
      name: "47",
      isRequired: true,
      title: "Как Вы оцениваете работу специалистов реанимационного отделения?",
      rateValues: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      minRateDescription: "Не удовлетворены",
      maxRateDescription: "Удовлеторены",
    },
  ],
};



const Mock2 = {
  cookieName: "",
  title: "Анкета для оценки удовлетворенности пациента условиями оказания медицинской помощи в условиях круглосуточного или дневного стационара" ,
    locale: 'ru',
     questions: [
    {
      type: "radiogroup",
      name: "1",
      title: "Удовлетворены ли Вы условиями пребывания в отделении?",
      isRequired: true,
      choices: ["Да", "Нет"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "2",
      title: "Удовлетворены ли Вы отношением персонала во время лечения в отделении (доброжелательность, вежливость)?",
      isRequired: true,
      choices: ["Да", "Нет"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "3",
      title: "Сколько времени Вы провели в ожидании Вашего лечащего врача после госпитализации в отделение?",
      isRequired: true,
      choices: ["Более 2 часов", "От 1 до 2 часов", "От 30 минут до часа", "Менее 30 минут"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "4",
      title: "Где Вы ожидали первичного осмотра лечащего врача?",
      isRequired: true,
      hasOther: true,
      otherText: "Другое",
      choices: ["В коридоре", "В палате"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "5",
      title: "Кто проводил Ваш первичный осмотр?",
      isRequired: true,
      choices: ["Ваш лечащий врач", "Помощник врача (ординатор)","Дежурный врач"],
      colCount: 0,
    },
    {
      type: "html",
      name: "6",
      title: "<h3>Оцените от 1 до 10 действия Вашего врача во время госпитализации</h3>",
      isRequired: false,
      colCount: 0,
    },
    {
      type: "rating",
      name: "7",
      title: "Вас внимательно выслушали",
      isRequired: true,
      choices: [],
      colCount: 0,
    },
    {
      type: "rating",
      name: "8",
      title: "Вашей проблеме уделили должное внимание",
      isRequired: true,
      choices: [],
      colCount: 0,
    },
    {
      type: "rating",
      name: "9",
      title: "Вам ответили на все Ваши вопросы",
      isRequired: true,
      choices: [],
      colCount: 0,
    },
    {
      type: "rating",
      name: "10",
      title: "Врач был учтив и вежлив",
      isRequired: true,
      choices: ["Пациент", "Родственник"],
      colCount: 0,
    },
    {
      type: "rating",
      name: "11",
      title: "Умение расположить к себе пациента",
      isRequired: true,
      choices: ["Пациент", "Родственник"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "12",
      title: "После выписки врач объяснил Вам свои рекомендации?",
      isRequired: true,
      choices: ["Да", "Нет","Частично","Только после Вашей просьбы"],
      colCount: 0,
    },
    {
      type: "rating",
      name: "13",
      title: "Насколько Вы удовлетворены качеством выполнения обязанностей младшим (санитарки, буфетчицы) и средним (медицинские сестры) медицинским персоналом Вашего отделения?",
      isRequired: true,
      choices: [],
      colCount: 0,
    },
    {
      type: "rating",
      name: "14",
      title: "Насколько Вы удовлетворены питанием во время пребывания в НМИЦ?",
      isRequired: true,
      choices: [],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "15",
      title: "Были ли отмечены по отношению к Вам нарушения этики (грубость, невежливое обращение) со стороны медицинского персонала?",
      isRequired: true,
      choices: ["Да", "Нет"],
      colCount: 0,
    },
    {
      type: "radiogroup",
      name: "16",
      title: "Случались ли конфликтные ситуации в отделении?",
      isRequired: true,
      choices: ["Да", "Нет"],
      colCount: 0,
    },
    {
      type: "text",
      name: "17",
      title: "Укажите Ваши замечания, предложения для улучшения работы отделения",
      isRequired: true,
      colCount: 0,
    },
    ]
    }




    const Mock3 = {
      cookieName: "",
      title: "Анкета для оценки удовлетворенности пациента условиями оказания медицинской помощи при проведении диагностических процедур или приеме врача в клинико-диагностическом отделении, в амбулаторных подразделениях" ,
        locale: 'ru',
         questions: [
        {
          type: "radiogroup",
          name: "1",
          title: "Удовлетворены ли Вы условиями пребывания во время ожидания приема врача?",
          isRequired: true,
          choices: ["Да", "Нет"],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "2",
          title: "Что именно Вас не удовлетворяет?",
          visibleIf: "{1}='Нет'",
          isRequired: true,
          hasOther: true,
          otherText: "Другое",
          choices: ["Отсутствие свободных мест ожидания", "Состояние гардероба","Состояние туалета", "Отсутствие питьевой воды","Санитарные условия"],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "3",
          title: "Врач Вас принял вовремя?",
          isRequired: true,
          choices: ["Да","Нет"],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "4",
          visibleIf: "{3}='Нет'",
          title: "Сколько времени Вы провели в очереди на прием к врачу от назначенного Вам времени",
          isRequired: true,
          choices: ["Более 2 часов", "От 1 до 2 часов","От 30 минут до часа","Менее 30 минут"],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "5",
          title: "Удовлетворены ли Вы навигацией внутри НМИЦ (предоставлением информации о размещении кабинетов медицинских работников, лабораторных и диагностических подразделений, санитарно-гигиенических помещений и др.)?",
          isRequired: true,
          choices: ["Да", "Нет"],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "6",
          title: "Кто проводил Ваш первичный осмотр?",
          isRequired: true,
          choices: ["Врач, к которому Вы записались на прием", "Другой врач","Помощник врача (ординатор)"],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "7",
          title: "Соблюдена ли во время осмотра личная тайна? (использование ширм, жалюзи, закрытие кабинета на ключ)",
          isRequired: true,
          choices: ["Да","Нет"],
          colCount: 0,
        },
        {
          type: "html",
          name: "7",
          title: "<h3>Оцените от 1 до 10 действия Вашего врача при осмотре</h3>",
          isRequired: false,
          colCount: 0,
        },
        {
          type: "rating",
          name: "8",
          title: "Вас внимательно выслушали",
          isRequired: true,
          choices: [],
          colCount: 0,
        },
        {
          type: "rating",
          name: "9",
          title: "Вашей проблеме уделили должное внимание",
          isRequired: true,
          choices: [],
          colCount: 0,
        },
        {
          type: "rating",
          name: "10",
          title: "Вам ответили на все Ваши вопросы",
          isRequired: true,
          choices: [],
          colCount: 0,
        },
        {
          type: "rating",
          name: "11",
          title: "Врач был учтив и вежлив",
          isRequired: true,
          choices: [],
          colCount: 0,
        },
        {
          type: "rating",
          name: "12",
          title: "Умение расположить к себе пациента",
          isRequired: true,
          choices: [],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "13",
          title: "После осмотра врач объяснил Вам свои рекомендации?",
          isRequired: true,
          choices: ["Да", "Нет","Частично","Только после Вашей просьбы"],
          colCount: 0,
        },
        {
          type: "rating",
          name: "14",
          title: "Насколько Вы удовлетворены работой регистратуры?",
          isRequired: true,
          choices: [],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "15",
          title: "Были ли отмечены по отношению к Вам нарушения этики (грубость, невежливое обращение) со стороны медицинского персонала?",
          isRequired: true,
          choices: ["Да","Нет"],
          colCount: 0,
        },
        {
          type: "radiogroup",
          name: "16",
          title: "Случались ли конфликтные ситуации во время нахождения в клинико-диагностическом отделении?",
          isRequired: true,
          choices: ["Да", "Нет"],
          colCount: 0,
        },
        {
          type: "rating",
          name: "17",
          title: "Отметьте, насколько Вы удовлетворены оказанной медицинской помощью в НМИЦ",
          isRequired: true,
          choices: [],
          colCount: 0,
        },
        {
          type: "text",
          name: "18",
          title: "Укажите Ваши замечания, предложения для улучшения работы отделения",
          isRequired: true,
          colCount: 0,
        },
        ]
        }
    